### ISSUE TITLE
Problem libraries/Breadcrumbs.php

### ISSUE THREAD

**Issue by syscoid** [ci2backend/ci2backend#2]
Issue for PHP7:
Severity: Notice Message: Only variables should be passed by reference Filename: libraries/Breadcrumbs.php

must changes Line 126 :
if (end(array_keys($this->breadcrumbs)) == $key) {

with this code:
$crumbs = array_keys($this->breadcrumbs);
$breadcrumbs = end($crumbs);

if ($breadcrumbs == $key) {

**Comment by Kunshin** [comment]
Thanks for your contribution, @syscoid 
I fixed this problem.

**Comment by syscoid** [comment]
No Problem.. 
I will help to solve & run good when using higher php version to run normally :)
