### ISSUE TITLE
Setup issue's, and beyond setup

### ISSUE THREAD

**Issue by dnsBlah** [ci2backend/ci2backend#6]
Hey guys,

I'm really interested in this system, but I have a few problems.
- I'm running on a VPS server with Plesk.
>PHP is installed through Plesk thus its a 'CGI' installation (meaning there is no apache_get_modules() available)

- I'm running multiple mysql instances on different ports
>missing the port setting

Anyways, I got through installation and login.
There are loads of locations where apache_get_modules() is being called, so.. I'm giving up.

I hope you can do something about this?
In my opinion checking the modules is not for you to do, but the webmaster's job.
If you mention all requirements before installation that should be enough.

Resulting a more universal system :)

Please let me know, I'm really interested!

**Comment by syscoid** [comment]
Check the php running & create 1 file on root html like this:
<?php
phpinfo();
?>
see the modules added & running on system.
for mysql u must check on default port 3306 for normally running mysql.

if you run web server with Apache2, check module on console like this:
apachectl -t -D DUMP_MODULES

and if want to print on php, like this:
<?php
print_r(apache_get_modules());
?>

dont worry.. If there are difficulties, you can contact me directly via email
I will check for server if allowed

**Comment by syscoid** [comment]
Check the php running & create 1 file on root html like this:
```
<?php
phpinfo();
?>
```

see the modules added & running on system.
for mysql u must check on default port 3306 for normally running mysql.

if you run web server with Apache2, check module on console like this:
apachectl -t -D DUMP_MODULES

and if want to print on php, like this:
```
<?php
print_r(apache_get_modules());
?>
```

dont worry.. If there are difficulties, you can contact me directly via email
I will check for server if allowed

**Comment by dnsBlah** [comment]
Hi syscoid, I don't think you understand the 'issue' :)
"PHP is installed through Plesk thus its a 'CGI' installation (meaning there is no apache_get_modules() available)"

And I already removed the apache_get_modules() check at installation, as I know I qualify for the modules.
But throughout the project there are a bunch more apache_get_modules() checks. So I stopped.
Regarding to mySQL, like I told, I'm missing the option to customize the port.
Because I am running multiple mySQL instances, resulting in different ports for each instance.
So I added it manually in the source.

I just hope that the apache_get_modules() calls can be removed, and the mysql port option can be added, as it will make the project more universal :)
As currently it's too much hassle to get it up and running 100% for my environment.

Anyways, please elaborate you answer as I don't see any relation between my 'issue' and your answer, maybe my 'issue' is not clear enough ?

**Comment by Kunshin** [comment]
Thank you guys for raising this issue. We will solve it as soon as possible
